incidentes:
  - id
  - numero_alerta
  - evento_resumo
  - data_evento
  - o_que_aconteceu
  - por_que_aconteceu
  - foto_url
  - anexos_url

acoes_bloqueio:
  - id
  - id_incidente
  - descricao_acao

plano_de_acao_abrangencia:
  - id
  - id_acao_bloqueio
  - unidade_operacional
  - responsavel_email
  - co_responsavel_email
  - prazo_inicial
  - status
  - data_conclusao
  - url_evidencia
  - detalhes_conclusao

usuarios:
  - email
  - nome
  - role
  - unidade_associada

auditoria:
  - timestamp
  - user_email
  - action
  - details

unidades:
  - nome_unidade
  - spreadsheet_id
  - folder_id
