name: Envio Diário do Relatório de Vencimentos

on:
  schedule:
    - cron: '0 11 * * *'
  workflow_dispatch:

jobs:
  send_notification_request:
    runs-on: ubuntu-latest
    
    steps:
      - name: Chamar o webhook do app Streamlit
        run: |
        
          curl -sSL --fail "${{ secrets.STREAMLIT_APP_URL }}/webhook_handler"
