# Nome do workflow que aparecerá na aba "Actions" do seu repositório
name: Envio Diário de Notificações de Ações Atrasadas

on:
  schedule:
    # Executa todos os dias às 09:00 UTC (06:00 no Horário de Brasília).
    # Ajuste o horário conforme sua necessidade.
    - cron: '0 9 * * *'
  
  # Permite a execução manual pela interface do GitHub
  workflow_dispatch:

jobs:
  run-python-script:
    # Executa em uma máquina virtual Linux (Ubuntu) mais recente
    runs-on: ubuntu-latest
    
    steps:
      # 1. Baixa o código do seu repositório para a máquina virtual
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Configura o ambiente Python na versão especificada
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # Mantém a versão do Python consistente

      # 3. Instala as dependências do projeto a partir do requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # 4. Executa o script de notificação a partir de sua nova localização
      - name: Run email notifier script
        env:
          # Credenciais para acessar Google Sheets
          GCP_SERVICE_ACCOUNT_CREDENTIALS: ${{ secrets.GCP_SERVICE_ACCOUNT_CREDENTIALS }}
          
          # Credenciais para o envio de e-mail via SMTP
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
          RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}

          # --- ADIÇÃO ESSENCIAL AQUI ---
          # Passa o ID da planilha como variável de ambiente
          MATRIX_SPREADSHEET_ID: ${{ secrets.MATRIX_SPREADSHEET_ID }}
          
          # Credenciais do Supabase
          DATABASE_CONNECTION_STRING: ${{ secrets.DATABASE_CONNECTION_STRING }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          
        run: python .github/scripts/email_notifier.py
