name: Envio Diário do Relatório de Vencimentos

on:
  # Gatilho 1: Agendamento (schedule)
  schedule:
    # Executa todos os dias às 11:00 UTC.
    # 11:00 UTC corresponde a 08:00 no Horário de Brasília (BRT / GMT-3).
    # Use um site como "crontab.guru" para encontrar o horário UTC correto para você.
    # Formato: (minuto hora dia-do-mês mês dia-da-semana)
    - cron: '0 12 * * *'
  
  # Gatilho 2: Manual (workflow_dispatch)
  # Isso adiciona um botão "Run workflow" na aba "Actions" para você testar
  # ou executar o envio manualmente a qualquer momento.
  workflow_dispatch:

jobs:
  # Nome do "trabalho" a ser executado
  send_notification_request:
    # O tipo de máquina que vai executar a tarefa (padrão do GitHub)
    runs-on: ubuntu-latest
    
    steps:
      # Nome do passo
      - name: Chamar o webhook do app Streamlit
        # O comando que será executado no terminal da máquina virtual
        # Ele usa 'curl' para fazer uma requisição HTTP para a URL do seu app.
        # Os valores entre ${{ ... }} são os "Secrets" que você vai configurar.
        run: |
          curl --fail "${{ secrets.STREAMLIT_APP_URL }}?trigger=${{ secrets.STREAMLIT_TRIGGER_SECRET }}"
