[database]
connection_string = "postgresql://postgres:[YOUR-PASSWORD]@db.qhkfkffkaqihlhcfildx.supabase.co:5432/postgres"
[t4CliyZGsOh1VBXI]


[supabase]
url = "https://qhkfkffkaqihlhcfildx.supabase.co"
key = "sua-anon-key-aqui"
service_role_key = "eyJhbGc..." # <<< ADICIONE (encontre no Supabase > Settings > API)